### ISSUE TITLE
Problem 

### ISSUE THREAD

**Issue by XFizzer** [thebigsmileXD/SimpleSpawner#1]
25.01 20:18:56 [Server] Server thread/EMERGENCY An unrecoverable error has occurred and the server has crashed. Creating a crash dump
25.01 20:18:56 [Server] INFO Fatal error: Declaration of xenialdan\SimpleSpawner\block\MonsterSpawner::getDrops(pocketmine\item\Item $item) must be compatible with pocketmine\block\Block::getDrops(pocketmine\item\Item $item): array in phar:///plugins/SimpleSpawner_v1.0.2.phar/src/xenialdan/SimpleSpawner/block/MonsterSpawner.php on line 113

**Comment by inxomnyaa** [comment]
blame the core you have. i ain't gonna support it.

**Comment by daniktheboss** [comment]
Damn

**Comment by inxomnyaa** [comment]
@XFizzer use the source and edit that specific line yourself
