### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kosovopolje** [thebigsmileXD/SimpleSpawner#10]
Hello, i installed the plugin, it works fine until i place the spawner, it doesnt seem to spawn mobs, do i need another plugin as a addon?

**Comment by thebigsmileXD** [comment]
No. But you either need plugins that register the entities you want to spawn, or a core that has them. I suggest ClearSky/PocketMine-MP, there are all entities up to MCPE 1.1 added.

**Comment by optimusprime338** [comment]
@thebigsmileXD will it good be good if I use pure entities? or Teaspoon? in pmmp

**Comment by thebigsmileXD** [comment]
yes
