### ISSUE TITLE
Error Please Fix

### ISSUE THREAD

**Issue by OfficialLilKev** [thebigsmileXD/SimpleSpawner#4]
Fatal error: Declaration of xenialdan\SimpleSpawner\block\MonsterSpawner::getDrops(pocketmine\item\Item $item) must be compatible with pocketmine\block\Block::getDrops(pocketmine\item\Item $item): array in /plugins/SimpleSpawner-master/src/xenialdan/SimpleSpawner/block/MonsterSpawner.php on line 113

Im using GenisysPro

**Comment by inxomnyaa** [comment]
Todo: also give correct spawner name when dropped

**Comment by daniktheboss** [comment]
close please

**Comment by inxomnyaa** [comment]
@daniktheboss only because its fixed ;)
