### ISSUE TITLE
How to charge players

### ISSUE THREAD

**Issue by draco123493** [thebigsmileXD/SimpleSpawner#5]
Hello i have this installed and it is working fine, but i want to charge players certain amounts for getting a spawner, how do i do that? Please reply ASAP thank you.
Note: I am using EconomyAPI

**Comment by inxomnyaa** [comment]
Write an extra plugin, that gives the player the permission for /simplespawner get for 1 time i guess..

**Comment by draco123493** [comment]
Can you suggest which?

**Comment by inxomnyaa** [comment]
_write_

**Comment by provsalt** [comment]
use slapper insert command 
/slapper create player [NaneHere]
/Slapper edit id addcommand rca {player} simperspawner get args
/slapper edit sameid addcommand rca {player} pay YourUsername Amount

**Comment by provsalt** [comment]
also im using economyapi
